development:
  adapter: async

#   adapter: redis
#   url: redis://localhost:6379/1
#   channel_prefix: townfo_development

test:
  adapter: test

production:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: townfo_production
